
name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Buildozer in Docker to build APK (this may take long)
        run: |
          docker run --rm -v "${{ github.workspace }}":/home/user/host -w /home/user/host kivy/buildozer:latest             /bin/bash -c "buildozer -v android debug"
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: bdg-apk
          path: bin/*.apk
